// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI0HSxK5DP-MtaF786yWj2pIJIzvHAxv4',
    appId: '1:368975565731:web:5ea8ffcb17443655078016',
    messagingSenderId: '368975565731',
    projectId: 'ayusri-app',
    authDomain: 'ayusri-app.firebaseapp.com',
    databaseURL: 'https://ayusri-app-default-rtdb.firebaseio.com',
    storageBucket: 'ayusri-app.firebasestorage.app',
    measurementId: 'G-63F3M60R3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-z2XY6Lfb6FPjbyIZAYU_04uPSSRyvL4',
    appId: '1:368975565731:android:a43480e4fc12dcd0078016',
    messagingSenderId: '368975565731',
    projectId: 'ayusri-app',
    databaseURL: 'https://ayusri-app-default-rtdb.firebaseio.com',
    storageBucket: 'ayusri-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxKPgeacosaD1vvvaGyLeOwJrBLEk7frc',
    appId: '1:368975565731:ios:afc833effd78e78b078016',
    messagingSenderId: '368975565731',
    projectId: 'ayusri-app',
    databaseURL: 'https://ayusri-app-default-rtdb.firebaseio.com',
    storageBucket: 'ayusri-app.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanjaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxKPgeacosaD1vvvaGyLeOwJrBLEk7frc',
    appId: '1:368975565731:ios:afc833effd78e78b078016',
    messagingSenderId: '368975565731',
    projectId: 'ayusri-app',
    databaseURL: 'https://ayusri-app-default-rtdb.firebaseio.com',
    storageBucket: 'ayusri-app.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanjaa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI0HSxK5DP-MtaF786yWj2pIJIzvHAxv4',
    appId: '1:368975565731:web:e0cdda80e10f9e31078016',
    messagingSenderId: '368975565731',
    projectId: 'ayusri-app',
    authDomain: 'ayusri-app.firebaseapp.com',
    databaseURL: 'https://ayusri-app-default-rtdb.firebaseio.com',
    storageBucket: 'ayusri-app.firebasestorage.app',
    measurementId: 'G-SE8WDB35QY',
  );
}
