// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS49raWYDUDTEk4jlK0EREGbkhdURDDPo',
    appId: '1:696146121995:web:4bac5d088a145232b5fe0e',
    messagingSenderId: '696146121995',
    projectId: 'fasum-app-5a410',
    authDomain: 'fasum-app-5a410.firebaseapp.com',
    storageBucket: 'fasum-app-5a410.firebasestorage.app',
    measurementId: 'G-8B8XDCP5N9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABK5D8jlD6UhlaKUcXLIHRIIk0zhlVxZ8',
    appId: '1:696146121995:android:57c189e8f8397843b5fe0e',
    messagingSenderId: '696146121995',
    projectId: 'fasum-app-5a410',
    storageBucket: 'fasum-app-5a410.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX96pCJWEXJOEL4IWIIn5BoxWqxH7iVFQ',
    appId: '1:696146121995:ios:39ae0fd8b7be01d3b5fe0e',
    messagingSenderId: '696146121995',
    projectId: 'fasum-app-5a410',
    storageBucket: 'fasum-app-5a410.firebasestorage.app',
    iosBundleId: 'com.example.fasumApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX96pCJWEXJOEL4IWIIn5BoxWqxH7iVFQ',
    appId: '1:696146121995:ios:39ae0fd8b7be01d3b5fe0e',
    messagingSenderId: '696146121995',
    projectId: 'fasum-app-5a410',
    storageBucket: 'fasum-app-5a410.firebasestorage.app',
    iosBundleId: 'com.example.fasumApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS49raWYDUDTEk4jlK0EREGbkhdURDDPo',
    appId: '1:696146121995:web:0e82690f8736d4fdb5fe0e',
    messagingSenderId: '696146121995',
    projectId: 'fasum-app-5a410',
    authDomain: 'fasum-app-5a410.firebaseapp.com',
    storageBucket: 'fasum-app-5a410.firebasestorage.app',
    measurementId: 'G-35D2PJ1FRY',
  );
}
