// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOKRmNMdjJmXvyI_3Lcte85Ju0YSqUysk',
    appId: '1:156339632899:web:9785700019346a4ace4736',
    messagingSenderId: '156339632899',
    projectId: 'ayu-app-67b38',
    authDomain: 'ayu-app-67b38.firebaseapp.com',
    databaseURL: 'https://ayu-app-67b38-default-rtdb.firebaseio.com',
    storageBucket: 'ayu-app-67b38.firebasestorage.app',
    measurementId: 'G-MYEG89B3PX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVQU7_jD5hib1WJXYocc_3aDYIHzdYI8E',
    appId: '1:156339632899:android:9843daa8d7c04edfce4736',
    messagingSenderId: '156339632899',
    projectId: 'ayu-app-67b38',
    databaseURL: 'https://ayu-app-67b38-default-rtdb.firebaseio.com',
    storageBucket: 'ayu-app-67b38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5PxUtPhwHvKG6nx2G_Sy6f-mXfrrz9HI',
    appId: '1:156339632899:ios:bcaadada713994a5ce4736',
    messagingSenderId: '156339632899',
    projectId: 'ayu-app-67b38',
    databaseURL: 'https://ayu-app-67b38-default-rtdb.firebaseio.com',
    storageBucket: 'ayu-app-67b38.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5PxUtPhwHvKG6nx2G_Sy6f-mXfrrz9HI',
    appId: '1:156339632899:ios:bcaadada713994a5ce4736',
    messagingSenderId: '156339632899',
    projectId: 'ayu-app-67b38',
    databaseURL: 'https://ayu-app-67b38-default-rtdb.firebaseio.com',
    storageBucket: 'ayu-app-67b38.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOKRmNMdjJmXvyI_3Lcte85Ju0YSqUysk',
    appId: '1:156339632899:web:b4a0e98458941aa1ce4736',
    messagingSenderId: '156339632899',
    projectId: 'ayu-app-67b38',
    authDomain: 'ayu-app-67b38.firebaseapp.com',
    databaseURL: 'https://ayu-app-67b38-default-rtdb.firebaseio.com',
    storageBucket: 'ayu-app-67b38.firebasestorage.app',
    measurementId: 'G-KPYXHD2X99',
  );
}
